const express = require('express')
const router = express.Router()
const upload = require('../middleware/upload')
const worka = require('../controllers/work')
router.get('/',worka.index)
router.post('/show',worka.show)
router.post('/findbysh',worka.findbystudentandhomework)
router.post('/addrendu',upload.single('rendu'),worka.add)
router.post('/update',worka.update)
router.post('/delete',worka.destroy)
module.exports = router